### ISSUE TITLE
neovide crashes on start-up (installed with snap on Fedora 34 & 35)

### ISSUE THREAD

**Issue by KarlLevik** [neovide/neovide#1060]
**Describe the bug**
neovide crashes during start-up when installed using snap on Fedora 34 and 35. 

**To Reproduce**
1. Use Fedora 34 or 35.
2. In a terminal, run "snap install neovide". (You will be prompted for admin password.) Or run "sudo snap install neovide" - same result.
3. Run "neovide" and observe crash:
```
thread 'main' panicked at 'Library libwayland-egl.so could not be loaded.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.28.6/src/egl.rs:48:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```
4. Run "RUST_BACKTRACE=1 neovide" and observe crash with backtrace:
```
thread 'main' panicked at 'Library libwayland-egl.so could not be loaded.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.28.6/src/egl.rs:48:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:1578:5
   3: core::option::Option<T>::expect
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:685:21
   4: <wayland_sys::egl::WAYLAND_EGL_HANDLE as core::ops::deref::Deref>::deref::__static_ref_initialize
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.28.6/src/egl.rs:48:9
   5: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
   6: lazy_static::lazy::Lazy<T>::get::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:31:29
   7: std::sync::once::Once::call_once::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sync/once.rs:261:41
   8: std::sync::once::Once::call_inner
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sync/once.rs:418:21
   9: std::sync::once::Once::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sync/once.rs:261:9
  10: lazy_static::lazy::Lazy<T>::get
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:30:9
  11: <wayland_sys::egl::WAYLAND_EGL_HANDLE as core::ops::deref::Deref>::deref::__stability
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:142:21
  12: <wayland_sys::egl::WAYLAND_EGL_HANDLE as core::ops::deref::Deref>::deref
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:144:17
  13: wayland_egl::WlEglSurface::new_from_raw
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-egl-0.28.6/src/lib.rs:49:19
  14: glutin::platform_impl::platform_impl::wayland::Context::new_raw_context
             at /root/.cargo/git/checkouts/glutin-28a8ef01504023c4/cf50967/glutin/src/platform_impl/unix/wayland.rs:119:13
  15: glutin::platform_impl::platform_impl::wayland::Context::new
             at /root/.cargo/git/checkouts/glutin-28a8ef01504023c4/cf50967/glutin/src/platform_impl/unix/wayland.rs:105:23
  16: glutin::platform_impl::platform_impl::Context::new_windowed
             at /root/.cargo/git/checkouts/glutin-28a8ef01504023c4/cf50967/glutin/src/platform_impl/unix/mod.rs:113:20
  17: glutin::windowed::<impl glutin::ContextBuilder<T>>::build_windowed
             at /root/.cargo/git/checkouts/glutin-28a8ef01504023c4/cf50967/glutin/src/windowed.rs:341:9
  18: neovide::window::window_wrapper::create_window
             at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:274:28
  19: neovide::main
             at /root/parts/neovide/build/src/main.rs:171:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
^C
```
5. Run "RUST_BACKTRACE=full neovide" and observe full backtrace:
```
thread 'main' panicked at 'Library libwayland-egl.so could not be loaded.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.28.6/src/egl.rs:48:37
stack backtrace:
   0:     0x55ab8d254cc0 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55ab8d254cc0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ab8d254cc0 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55ab8d254cc0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55ab8d196fbc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x55ab8d253294 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x55ab8d253ebb - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55ab8d253ebb - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55ab8d253ebb - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x55ab8d252e99 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x55ab8d252e99 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x55ab8d26cea8 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:     0x55ab8d26ce1c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55ab8d26cdcd - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x55ab8d041900 - core::panicking::panic_fmt::h12a3a3c256485fca
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:     0x55ab8d041ba2 - core::option::expect_failed::h7db74b1e3f5289b2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:1578:5
  16:     0x55ab8d2f838e - core::option::Option<T>::expect::h8168b96039ad7069
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/option.rs:685:21
  17:     0x55ab8d2f838e - <wayland_sys::egl::WAYLAND_EGL_HANDLE as core::ops::deref::Deref>::deref::__static_ref_initialize::h9d96f045ca5f88c1
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.28.6/src/egl.rs:48:9
  18:     0x55ab8d2f838e - core::ops::function::FnOnce::call_once::hf995503ae06d7fd7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
  19:     0x55ab8d2f838e - lazy_static::lazy::Lazy<T>::get::{{closure}}::h7a20a6da07f7e341
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:31:29
  20:     0x55ab8d2f838e - std::sync::once::Once::call_once::{{closure}}::h3eb256b0af521dc7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sync/once.rs:261:41
  21:     0x55ab8d04e418 - std::sync::once::Once::call_inner::hde8ba9bafe28b43e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sync/once.rs:418:21
  22:     0x55ab8d0ee9e0 - std::sync::once::Once::call_once::h72be678fed11efac
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sync/once.rs:261:9
  23:     0x55ab8d0ee9e0 - lazy_static::lazy::Lazy<T>::get::h879e5d81eba0c829
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:30:9
  24:     0x55ab8d0ee9e0 - <wayland_sys::egl::WAYLAND_EGL_HANDLE as core::ops::deref::Deref>::deref::__stability::hd274b06eb6b43738
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:142:21
  25:     0x55ab8d0ee9e0 - <wayland_sys::egl::WAYLAND_EGL_HANDLE as core::ops::deref::Deref>::deref::ha60e04f63af24397
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:144:17
  26:     0x55ab8d0ee9e0 - wayland_egl::WlEglSurface::new_from_raw::h6a83a8e67857c833
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-egl-0.28.6/src/lib.rs:49:19
  27:     0x55ab8d0ee9e0 - glutin::platform_impl::platform_impl::wayland::Context::new_raw_context::hbe18970c13079446
                               at /root/.cargo/git/checkouts/glutin-28a8ef01504023c4/cf50967/glutin/src/platform_impl/unix/wayland.rs:119:13
  28:     0x55ab8d0ee9e0 - glutin::platform_impl::platform_impl::wayland::Context::new::h90fb0d43a6f19c32
                               at /root/.cargo/git/checkouts/glutin-28a8ef01504023c4/cf50967/glutin/src/platform_impl/unix/wayland.rs:105:23
  29:     0x55ab8d0ee9e0 - glutin::platform_impl::platform_impl::Context::new_windowed::hea4b1b703091c0a9
                               at /root/.cargo/git/checkouts/glutin-28a8ef01504023c4/cf50967/glutin/src/platform_impl/unix/mod.rs:113:20
  30:     0x55ab8d0ee9e0 - glutin::windowed::<impl glutin::ContextBuilder<T>>::build_windowed::hddf56c0dedfddfc7
                               at /root/.cargo/git/checkouts/glutin-28a8ef01504023c4/cf50967/glutin/src/windowed.rs:341:9
  31:     0x55ab8d14383b - neovide::window::window_wrapper::create_window::hcf20f9fb48510576
                               at /root/parts/neovide/build/src/window/window_wrapper/mod.rs:274:28
  32:     0x55ab8d0d735d - neovide::main::h6e70023db0b1cd0a
                               at /root/parts/neovide/build/src/main.rs:171:5
  33:     0x55ab8d0e83b3 - core::ops::function::FnOnce::call_once::hf6a1d5d6f2a812dd
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:227:5
  34:     0x55ab8d0e83b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29430f71efff7f85
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:125:18
  35:     0x55ab8d0d1e84 - main
  36:     0x7fdf8b9ee0b3 - __libc_start_main
  37:     0x55ab8d054d1e - _start
  38:                0x0 - <unknown>
^C
```
**Expected behavior**
neovide should start up without crashing.

**Desktop (please complete the following information):**
 - OS: Fedora 34 and Fedora 35
 - Neovide Version 0.8.0
 - Neovim Version 0.5.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
TRACE [neovide] Neovide version: 0.8.0
INFO [neovide::bridge] Starting neovim with: Command { std: "/snap/neovide/120/usr/bin/nvim" "--embed", kill_on_drop: false }
INFO [neovide::bridge] Close watcher started
DEBUG [neovide::bridge::events] Ignored client type property: "methods"
DEBUG [neovide::bridge::events] Ignored client type property: "attributes"
INFO [neovide::bridge] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached

**Additional context**
It seems to work as expected when running "neovide" as the root user.

**Comment by LoipesMas** [comment]
It looks like some dependency of neovide can't find the `libwayland-egl.so` it wants. I'm not sure why running as root would work though. Maybe snap (or Fedora) handles lib per user? (e.g. root can have different version of libs from other users).

**Comment by KarlLevik** [comment]
I have a two other applications installed with snap (hugo and spotify), and both work OK running as my normal user.

Running "dnf install libwayland-egl" gives:
```
Package libwayland-egl-1.19.0-2.fc35.x86_64 is already installed.
Package libwayland-egl-1.19.0-2.fc35.i686 is already installed.
```

**Comment by KarlLevik** [comment]
I googled the error message and some pages mentioned  `$WAYLAND_DISPLAY`. I noticed my "normal" user had a value for this:
```bash
$ echo $WAYLAND_DISPLAY
wayland-0
```
... whereas my root user didn't. So therefore I tried:
```bash
$unset WAYLAND_DISPLAY
```
... and after that neovide starts up without crashing!

**Comment by AlphaTechnolog** [comment]
> ... and after that neovide starts up without crashing!

The problem is solved? Close the issue...

**Comment by dineshKumar777** [comment]
and after that neovide starts up without crashing!

-- Closing since its resolved now

**Comment by PolyMeilex** [comment]
The issue is obviously not solved, you just tricked neovide to think that there is no Wayland available on the machine...

**Comment by KarlLevik** [comment]
Agreed, disabling wayland is just a workaround, and a bad one at that. For example, it takes away the ability to paste text into the editor.

Would be great to get the snap version fixed properly.

**Comment by PolyMeilex** [comment]
Sadly I don't have much knowledge about snap, but hopefully someone else can look into it, so it would be nice to reopen this issue (that is as long as maintainers agree that this is indeed an issue)

BTW, `WINIT_UNIX_BACKEND=x11 neovide` is the proper less hacky way to force X11 in winit based apps without removing Wayland env variable.

**Comment by fredizzimo** [comment]
I know nothing about Snaps, but I'm quite sure that we need to add `libwayland-egl1` here https://github.com/neovide/neovide/blob/3efc3c1759c80368090e8f747b188b2155ea68f0/snap/snapcraft.yaml#L93-L109

**Comment by fredizzimo** [comment]
Note: you might be able to work around the problems by installing the snap in devmode `snap install --devmode` https://forum.snapcraft.io/t/snap-confinement/6233. If you do that it should output a debug output, with all unspecified interfaces, so, please post that log here.

**Comment by metacortexplus** [comment]
Same error, Fedora 36

**Comment by dreamerlzl** [comment]
Fedora 36, neovim 0.7.2, neovide 0.8, latest snap, kernel 5.18. The exact same problem and `unset WAYLAND_DISPLAY` saves my day.

**Comment by creamy-gurkin** [comment]
I just built neovide using
``` bash
cargo install --git https://github.com/neovide/neovide
```
Neovide was unresponsive and unworkably slow, doing:

``` bash
WINIT_UNIX_BACKEND=x11 neovide
```

Makes it work perfectly. Seems it's something more than just the snap.

Using Fedora 36

**Comment by mickey298** [comment]
Same errors on ubuntu22,kernel 5.15.0
BTW. Run neovide with `WINIT_UNIX_BACKEND=x11 neovide`  shows nvim version 0.6 even i installed neovide 0.8.0.

**Comment by dolosarafat** [comment]
any updates on this (ubuntu22.10)

**Comment by fredizzimo** [comment]
As mentioned earlier, it would be nice to see the output from `snap install --devmode neovide`, that should tell what's wrong.

**Comment by KarlLevik** [comment]
Since I originally reported this I've moved on to Fedora 37 but the problem persists.

I just tried to install with devmode but not seeing a lot of output?

```
# snap install --devmode neovide
neovide 0.8.0+git from Jack Frost (j4qfrost) installed
```
That was all the output I got from that command.

Snap info:
```
# snap info --verbose neovide
name:    neovide
summary: The snappiest vim editor you are likely to find.
health:
  status:  unknown
  message: health has not been set
publisher: Jack Frost (j4qfrost)
store-url: https://snapcraft.io/neovide
contact:   [redacted]
links:
  contact:
    - mailto:[redacted]
  website:
    - https://github.com/neovide/neovide
license: unset
description: |
  This is a simple graphical user interface for Neovim. Where possible there are some graphical
  improvements,
  but it should act functionally like the terminal UI.
commands:
  - neovide
notes:               
  private:           false
  confinement:       strict
  devmode:           true
  jailmode:          false
  trymode:           false
  enabled:           true
  broken:            false
  ignore-validation: false
base:         core20
snap-id:      TCgKjSjqlmhnmPrsfLsghfsXKvAA0IIB
tracking:     latest/stable
refresh-date: today at 16:39 GMT
channels:
  latest/stable:    0.8.0+git 2022-03-04 (132) 103MB -
  latest/candidate: ↑                                
  latest/beta:      0.8.0+git 2022-03-04 (132) 103MB -
  latest/edge:      0.8.0+git 2022-03-04 (132) 103MB -
installed:          0.8.0+git            (132) 103MB devmode
```

Snap connections:
```
# snap connections neovide
Interface       Plug                    Slot             Notes
desktop         neovide:desktop         :desktop         -
desktop-legacy  neovide:desktop-legacy  :desktop-legacy  -
unity7          neovide:unity7          :unity7          -
wayland         neovide:wayland         :wayland         -
x11             neovide:x11             :x11             -
```

**Comment by fredizzimo** [comment]
It looks like the snap itself is ok then, I should have read the latest comments in this thread a bit more carefully. It looks like it's a wayland problem. 

I haven't done any testing in wayland myself, well I tried to run it once, and it crashes on Arch Linux, the non-snap version. But that was just after I had setup wayland at all, so I assumed that it was some problems with that, I was going to do more testing of my rendering changes with wayland at some point, so that's why I set it up. But it looks like, I should do that sooner rather than later.

**Comment by PolyMeilex** [comment]
Can confirm that the state of this issue did not change for me, native version works fine under Wayland, snap still panics with `libwayland-egl.so could not be loaded` error. Ubuntu 22.10, Wayland, non-nvidia.

**Comment by fredizzimo** [comment]
That's perhpas not so suprising, since l can't see libwayland here https://github.com/neovide/neovide/blob/main/snap/snapcraft.yaml, but I have never made any snaps myself, so I might be wrong, and maybe it's not needed.

Strange that it does not report the errors as it should with [devmode](https://forum.snapcraft.io/t/snap-confinement/6233) though. Or maybe I'm reading the documentation wrong, since again no experience.

**Comment by jarkkojs** [comment]
I can confirm that issue exists in 2766fe7f84d4d1825d7399378fdd3b0e1ce7f4a6, which I installed by issuing: `cargo install --git https://github.com/neovide/neovide.git`. I'm running Ubuntu 22.10.

If the root cause is still not fully resolved, I'd suggest to add a remark to README.me, and a workaround:

```
WAYLAND_DISPLAY= neovide
```

This is less intrusive than `unset WAYLAND_DISPLAY` because it affects only the environment of the forked process (and also easier e.g. to put to .desktop files and similar).

**Comment by PolyMeilex** [comment]
> ```
> WAYLAND_DISPLAY= neovide
> ```
> 
> This is less intrusive than `unset WAYLAND_DISPLAY` because it affects only the environment of the forked process (and also easier e.g. to put to .desktop files and similar).

If we want to add this to readme I would prefer to use the variable that is actually meant for this: `WINIT_UNIX_BACKEND=x11`, it will tell neovide (or any other winit based app) that it should use X11 even tho Wayland is available. Thanks to that there is no need to modify socket variables.

**Comment by carpetaa** [comment]
Any updates? Came here from wslg in win11.

**Comment by fredizzimo** [comment]
The wayland support should be fixed with https://github.com/neovide/neovide/pull/1789, but I'm not sure if there are additional issues with the Snaps.

**Comment by carpetaa** [comment]
> The wayland support should be fixed with #1789, but I'm not sure if there are additional issues with the Snaps.

the release in snap is from 4 March 2022, can you update it to the latest?

**Comment by fredizzimo** [comment]
There’s some problem with the credentials on the CI for uploading. But you can download the produced snap directly from here https://github.com/neovide/neovide/actions/runs/5272491031

**Comment by carpetaa** [comment]
I've installed using snap with the local snap binary in wslg of Ubuntu 20 on Windows 11.
When I run neovide, nothing happens, and Tracelog:
```
2023-06-17 10:45:37 - Neovide panicked with the message 'Library libwayland-egl.so could not be loaded.'. (File: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-sys-0.30.1/src/egl.rs; Line: 45, Column: 37)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_start_main
  14: <unknown>
```

Installation is successful.
```
$ neovide --version
neovide 0.10.4
```
```
$ snap info --verbose neovide
name:    neovide
summary: The snappiest vim editor you are likely to find.
health:
  status:  unknown
  message: health has not been set
publisher: –
store-url: https://snapcraft.io/neovide
license:   unset
description: |
  This is a simple graphical user interface for Neovim. Where possible there are some graphical
  improvements,
  but it should act functionally like the terminal UI.
commands:
  - neovide
notes:
  private:           false
  confinement:       strict
  devmode:           false
  jailmode:          false
  trymode:           false
  enabled:           true
  broken:            false
  ignore-validation: false
base:         core20
tracking:     latest/stable
refresh-date: today at 19:44 CST
channels:
  latest/stable:    0.8.0+git  2022-03-04 (132) 103MB -
  latest/candidate: ↑
  latest/beta:      0.8.0+git  2022-03-04 (132) 103MB -
  latest/edge:      0.8.0+git  2022-03-04 (132) 103MB -
installed:          0.10.4+git             (x4)  95MB -
```

**Comment by fredizzimo** [comment]
Neovide 0.11.0 fully supports wayland. But please use the AppImage or another installation method. We have big problems with the Snap packages and will likely drop the support for that completely.

**Comment by fredizzimo** [comment]
The snap package is very outdated, and can most likely not be fixed without upstream help, or by some snap expert https://forum.snapcraft.io/t/need-help-with-the-snap-for-neovide/35978, until then I think we should remove the snap package completely.

Closing this for now.
