### ISSUE TITLE
Fonts render with significant spacing

### ISSUE THREAD

**Issue by dartacao** [neovide/neovide#1096]
**Describe the bug**
Most fonts render oddly in my machine. In particular, FiraCode NF has unusually large gaps between characters (see screenshots).

**To Reproduce**
1. Open Neovide with font as FiraCode\ NF, whatever height, on windows 10. Not sure if this is a reproducible bug on other machines.

Tried reinstalling FiraCode, using other ligature'd fonts like Iosevka. Similar issues with large gaps between chars.

**Expected behavior**
Fonts should render with no gaps between ligatures or characters in general.
For example, Wezterm renders FC NF (same font) as:
![image](https://user-images.githubusercontent.com/2131630/146268325-3b89bb70-7aaf-49e2-8bfe-0418a9030109.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/2131630/146268067-24caf5d2-031e-41c1-bdc2-473758a79353.png)
Note that characters in statusline are also unusually spaced, no matter the font size.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Neovide Version 0.8.0
 - Neovim Version 0.6.0

Logs:
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7722808/neovide_rCURRENT.log)
[neovide_r2021-12-15_21-29-49.log](https://github.com/neovide/neovide/files/7722807/neovide_r2021-12-15_21-29-49.log)

**Comment by exten** [comment]
1. change the font , code in `src/renderer/fonts/font_loader.rs`
like this `static DEFAULT_FONT: &[u8] = include_bytes!("../../../assets/fonts/Fira Code Regular Nerd Font Complete.otf");`
2. rebuilder

**Comment by dartacao** [comment]
> 1. change the font , code in `src/renderer/fonts/font_loader.rs`
> like this `static DEFAULT_FONT: &[u8] = include_bytes!("../../../assets/fonts/Fira Code Regular Nerd Font Complete.otf");`
> 2. rebuilder

I'm sorry but I don't quite understand what I should do to be honest...

**Comment by dartacao** [comment]
> 1. change the font , code in `src/renderer/fonts/font_loader.rs`
>        like this `static DEFAULT_FONT: &[u8] = include_bytes!("../../../assets/fonts/Fira Code Regular Nerd Font Complete.otf");`
> 
>     2. rebuilder

I think I did what you asked successfully. However, the issue seems to persist... Any other suggestions?

**Comment by dartacao** [comment]
![image](https://user-images.githubusercontent.com/2131630/147141682-37580f40-2290-44dd-91fc-2ced57c1943e.png)

Top left is Fira Code default, bottom left is Fira Code as shipped by neovide, bottom right is Fira Code with NF symbols included (patched in my system). I have negative ideas over what's going on, so any thing that I can try or solves this bug is greatly appreciated...

**Comment by dartacao** [comment]
Okay, so I believe I have figured some of this out. For some reason, on my system, ligatures always render with 1px spacing in between font glyphs, which is mildly annoying. I have no idea why. Font fallback for Fira Code and then another with all NF glyphs solves the huge spacing issue I saw (bottom right on screenshots above).

**Comment by fredizzimo** [comment]
For me the problem is the opposite, some fonts have too little spacing, to the point where some characters are overlapping, like the `wv` in the image below. The font used here is the DejaVuSansMono NF.  I installed it through scoop the nerd-fonts bucket, both variations `DejavuSansMono-NF-Mono` and `DejavuSansMono-NF` seem to have the problem.

![image](https://user-images.githubusercontent.com/9946255/147861678-b5b4e87f-2699-4850-888d-77aea3c47d77.png)

I also tried with the Fira Code NF, also downloaded through scoop, but for some reason that does not seem to cause problems for me.

I'm on Windows 11.

**Comment by fredizzimo** [comment]
I also tested in Linux through WSLG, and it has the same problem, the DejavuSansMono nerd font is too narrow. 

I also did some more tests, and the Fira Code font is also behaving in a similar way as for @dartacao on both both systems. But it only seems to affect the ligatures with the long arrows, normal arrows seems to be fine. But on the other hand notepad, the Windows 11 terminal and Visual Studio Code all do the same thing, so WezTerm might do something special there.

**Comment by fredizzimo** [comment]
I have looked a bit deeper into this. And at the moment I'm concluding that the issue I'm seeing is different from what @dartacao sees. 

For me the problem is that Neovide always rounds the font width down. For example in the example above the font size is 11, and the width should be 8.83 pixels wide (determined by calculating it by hand, and also verifying that the swash library, which Neovide uses returns the same) , but Neovide rounds down and render the character inside a box 8 pixels wide, which is obviously too narrow.

I tried adding rounding in the code, and the result is much better, but still wrong, since now the spacing becomes slightly too big.  

The solution should be quite simple, since the spacing between characters is much more important than the line height, which is always rounded up anyway. We just need to add another scale factor, that actually scales the whole font so that the letters are always integer sized width. I also checked the source code of the Windows terminal to check what they are doing, and they seem to be using the same idea, so I didn't check further.

I will now proceed to implement this, it's not as simple as it is on paper, since the Neovide fontloader takes a size parameter, but we need to query the information first, so that the extra scale factor can be added, and then load the font.

But as I said, unfortunately that should not fix the original issue, since as far as I understand, the current Neovide code will always render the correct spacing or too narrow.

**Comment by fredizzimo** [comment]
I created this pull request https://github.com/neovide/neovide/pull/1116, it fixes my problem. @dartacao, you can test it but I don't think it fixes your problem.

**Comment by dartacao** [comment]
@fredizzimo For some reason I had some suspicion that it was some rounding issue, maybe with how height and width interact. Since you can't define width from neovide (though nvim allows it, it's a small issue), I couldn't test this.

Is it possible that the start of the glyph is rounded up but the end is rounded down, so that a single pixel difference is incorrectly added?
Something like:
Glyph starts at px0
Width is 8.35, next glyph should start at 8.35 but starts at 9?

I'm not sure if this is how rendering works but it would explain my issue at least?

**Comment by fredizzimo** [comment]
There was definitely a rounding issue, but it was going the opposite direction, because it uses the standard Rust integer cast rules, which unless I'm totally mistaken always rounds towards zero. So the next glyph would start too close to the next one, not too far like you are experiencing. 

The pull requests that I made, fixes this, so that the whole font is scaled very slightly and the width becomes an exact integer, so there are no rounding issues in the horizontal direction anymore. 

But I suspect, that you have a slightly different version of the Fira Code Nerd font, so that the average character width, which Neovide is trying to use to determine the character width reports something else than the actual width of the normal characters.

Actually if you post your logfile, I can check that, and if you can use my pull request there should be even more information in the logs.

**Comment by fredizzimo** [comment]
I updated the pull request https://github.com/neovide/neovide/pull/1116, with some code I believe will fix your issue, @dartacao.

**Comment by dartacao** [comment]
I will try it out as soon as i get back to my desktop, as my laptop doesn't experience this problem :)

**Comment by dartacao** [comment]
I am officially at a loss. It did not fix it, in fact as far as I can see it is mostly the same as before. I downloaded neovide from GH actions, latest build possible. No success :( @fredizzimo 
Even with -- --clean and no font selected (it should default to firacode), drawing ------ in the scratch pad returns a dash with 1 pixel spacing in between

**Comment by Kethku** [comment]
dash + spacing is potentially a ligature issue rather than spacing.

Can you paste screenshot comparisons with some basic reference text editor configured to the same font?

**Comment by dartacao** [comment]
![image](https://user-images.githubusercontent.com/2131630/148467047-f90d3c6a-206b-4f08-a9eb-928d3e51a4b5.png)
Top to bottom on screenshot:
Settings screen with Fira Code at 16pt
Neovide default (-- --clean)
Neovide, my config
WezTerm, nvim running on it, same exact text

**Comment by dartacao** [comment]
![image](https://user-images.githubusercontent.com/2131630/148468503-5ddc8d23-3fc9-4de1-827f-34fc4ef9bae0.png)

Here's why I suspect this is not a ligatures issue completely, or could be 2 separate problems entirely: some characters (such as the battery indicator on the bottom right of the screen) have a similarly large spacing in between. Top is wezterm, bottom is neovide.

**Comment by Kethku** [comment]
@fredizzimo is it possible this is the rounding issue? I also noticed you compared to wezterm @dartacao could you try configuring notepad and pasting a comparison there?

For comparison here is my machine with Cascadia Code PL at 11px
![image](https://user-images.githubusercontent.com/3323631/148470295-ebe76e83-98d3-4433-bba9-466efd7581be.png)
To my eyes these are identical (even including the ligature error at the start which is fascinating)

**Comment by dartacao** [comment]
![image](https://user-images.githubusercontent.com/2131630/148471488-8648d584-a2e7-4404-9617-5d7c18a45a2b.png)

Here it is, notepad and neovide.

**Comment by Kethku** [comment]
wild. Ok I'll do some more investigation although its hard when I can't repro... maybe I'm running an old build...

**Comment by dartacao** [comment]
> wild. Ok I'll do some more investigation although its hard when I can't repro... maybe I'm running an old build...

https://github.com/neovide/neovide/actions/runs/1662006400 I downloaded my build from here if you want to double check it. In any case, it's a very weird bug, as the same exact config produces different results on my Desktop (AMD RX480 GPU, FX-8350 CPU) than it does on my laptop (2019 intel i5, integrated gpu iirc). It's a super annoying visual glitch that I can't for the life of me figure out.

Also, note the battery indicator thing... It's got some weird spacing, that might help track it down.

**Comment by Kethku** [comment]
I'm also noticing that its flaky. Any chance your desktop has a higher dpi? My work laptop doesn't have this problem (even when docked) but this looks familiar on my desktop. I may be able to reproduce it there

**Comment by dartacao** [comment]
DPI is probably lower on the desktop to be honest, since they have the same resolution (1920x1080) but the desktop screen is much larger (13.3" vs 21", something like that).

**Comment by fredizzimo** [comment]
I’m not at the computer now to check, but it’s possible that it’s an antialiasing issue. The gap does not seem to be completely at the background color and since the glyphs are generated individually there’s a chance that the antialiasing goes a bit into the line at the edge, between the ligature characters.

I’m not sure how the antialiasing should be handled though.

**Comment by dartacao** [comment]
![image](https://user-images.githubusercontent.com/2131630/148534936-b3d9bcd7-1301-4158-9a08-ccd56a517add.png)

I did some more digging. The issue disappears for h > 35, as evidenced by the picture. Top is `FiraCode NF:h35`, `FiraCode NF:h36`. Tried most up to 64, ligatures have no issues above that threshold.

Is this consistent with an antialiasing issue?

**Comment by fredizzimo** [comment]
It might be, but it could also be some rounding issue, or something entirely different. The good news is that I have now been able to reproduce it on my work machine. So I will probably be able to fix it during the weekend.

**Comment by fredizzimo** [comment]
Setting the antialiasing to `Edging::Alias` (looks very bad since there's no antialiasing), or `Edging::Alias` instead of `Edging::SubpixelAntiAlias` fixes the issue, at least for me.

In addition to fixing the colors https://github.com/neovide/neovide/issues/1102, the text is also slightly sharper on my system with regular antialiasing. But some small font features like the decoration on top of the firacode g gets distorted and blurry. But I still prefer it slightly over the subpixel aliasing because of the colors and sharpness on my monitor. But the situation could be different on other monitors, monitor types, dpi, preference and so on. So I'm not sure if we can change over to use that, or if we need to try to find some workarounds for the issue.

**Comment by dartacao** [comment]
Would it be difficult to add some vimscript/lua option for that (something like `vim.g.neovide_antialiasing`, defaulting to whatever is the compiled AA option now and allowing the user to choose what looks best for their system?

I'll try changing to Edging::AntiAlias and recompile, see if that solves it in any case.

**Comment by LoipesMas** [comment]
`Edging::AntiAlias` fixes the gap in "border lines" ("———") for me too.
Making a setting for antialiasing is a bit more challenging, because it requires reloading the fonts on change. But it should be doable.

**Comment by dartacao** [comment]
It does fix it for me as well. A command line argument or an environment variable both seem off for a visual tweak, for some reason. 
In any case, the issue has been found, and I'm  happy with that. Thanks for the help everyone. 😄

**Comment by dartacao** [comment]
Since the font is being reloaded in any case, why not add a font option in the guifont setting to change the AA? Thats probably easier than reloading on demand and doesn't use an additional option. Something like "set guifont=FiraCode NF:h16:aaX", sets the AA level to whatever is wanted

**Comment by Kethku** [comment]
Its wild and frustrating to me how many issues the subpixel antialiasing seems to cause. The right course of action is definitely to add an option. I can spend some time building that soon. But in the meantime, we should probably just swap to normal antialiasing. I will create a PR for this.

**Comment by Kethku** [comment]
Mmmk I just pushed to main the swap. I will create another issue to add an option for it.

**Comment by A-Lamia** [comment]
I think I'm still having this issue but vertically ? 
![image](https://user-images.githubusercontent.com/6450181/193768343-b7894e3e-c321-4834-b799-e8432ac5a8f6.png)

**Comment by fredizzimo** [comment]
I don't see any issues there, notice how `(` and `[` are almost touching, any closer would likely look very cramped.

**Comment by A-Lamia** [comment]
@fredizzimo yeah it seems to be the font the confusing part is it doesn't happen with Firacode_NF but with VictorMono_NF but on windows terminal it works fine,
https://ss.lamia.io/i/explorer_iUlN8I4yn.png
