### ISSUE TITLE
Neovide process not fully detaching from terminal

### ISSUE THREAD

**Issue by bpandreotti** [neovide/neovide#1122]
**Describe the bug**
When running neovide (without passing the `--nofork` flag) the spawned process doesn't detach from the terminal.

**To Reproduce**
1. Run neovide from a terminal emulator without the `--nofork` flag
2. Exit the terminal with `exit`
3. See that the terminal emulator window will not close until neovide is closed

**Expected behavior**
I expected the terminal window to close without having to close neovide.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: 0.8.0
 - Neovim Version: v0.6.0-dev

**Additional context**
I believe this happens because neovide does not override stdin/stdout/stderr when spawning the new process:

https://github.com/neovide/neovide/blob/d220477b7379335968d972975e562aefe5061383/src/main.rs#L213-L217

By default, stdin/stdout/stderr inherit from the parent process, so they remain attached to the terminal session, preventing it from closing. Redirecting them to `/dev/null` seems to fix the problem:

```rust
assert!(process::Command::new(current_exe)
    .stdin(process::Stdio::null())
    .stdout(process::Stdio::null())
    .stderr(process::Stdio::null())
    .arg("--nofork")
    .args(env::args().skip(1))
    .spawn()
    .is_ok());
```

This was only tested on Linux. Should I make a PR?

**Comment by Kethku** [comment]
Yes. A PR should let us test it on other platforms. Thanks for looking into this!

**Comment by LoipesMas** [comment]
What terminal emulator do you use? Because I thought I didn't have this issue, but I tried other terminal emulators and can reproduce this on kitty. But it doesn't happen on st or alacritty.

**Comment by bpandreotti** [comment]
I do in fact use kitty, and I first encountered the issue on it. But I also tested this in gnome terminal and I could reproduce it there as well.

**Comment by fredizzimo** [comment]
This should be fixed by https://github.com/neovide/neovide/commit/98e1a72fe60cf69b7cc381477a3fcf88c307174b

**Comment by SyedAhkam** [comment]
This issue still persists on windows systems. Tested on powershell, cmd, and the windows terminal.

https://user-images.githubusercontent.com/52673095/151034354-b05e8a13-806b-4f28-a609-08181b87b3c9.mp4

**Comment by fredizzimo** [comment]
I'm re-opening this, since that's clearly a problem still on Windows

On Windows we actually do the opposite, but I guess that's so that we can see error messages. 
https://github.com/neovide/neovide/blob/dd74ff42394ac2f309108ccc0f53674cfaa8525b/src/main.rs#L198-L205

I guess in order to do the opposite, once we are ready for it, we need to call [FreeConsole](https://docs.microsoft.com/en-us/windows/console/freeconsole)

**Comment by Kethku** [comment]
Yeah this is absolutely a bug... I will fiddle with this and see what I can come up with

**Comment by Kethku** [comment]
https://github.com/neovide/neovide/pull/1178 I think this fixes it.

This doesn't print errors to the console though. @fredizzimo do you have any ideas what to do for that case? I don't know how to enable printing to the console while still detaching so that the parent can close...

**Comment by fredizzimo** [comment]
You could try to flush the output before detaching. Also did you try keeping the attach where it was, and calling `FreeConsole` from the `maybedisown` function, to emulate the same behaviour as on other systems?

**Comment by Kethku** [comment]
This is a great idea. I'll look into it

**Comment by SyedAhkam** [comment]
> #1178 I think this fixes it.
> 
> This doesn't print errors to the console though. @fredizzimo do you have any ideas what to do for that case? I don't know how to enable printing to the console while still detaching so that the parent can close...

I can confirm. That does fix it.

**Comment by Kethku** [comment]
Fixed in main.

**Comment by abbygriffiths** [comment]
This issue seems to have resurfaced on Windows. I've tried both cmd and powershell and the issue is present in both shells. Running `neovide` without any flags, or even with an explicit `--fork` flag does not properly detach the Neovide process from shell, and I can only issue additional commands to the shell after closing Neovide.

Details:
OS: Windows 10 22H2 (19045.4170)
Shell: CMD/Powershell Core 7.4.1/Powershell Desktop 5.1
Neovide version: 0.12.2
Neovim version: 0.9.5
