### ISSUE TITLE
CTRL+/ not working

### ISSUE THREAD

**Issue by BestChinchilla** [neovide/neovide#1481]
**Describe the bug**
CTRL+/ not working

**To Reproduce**
1. Write ```noremap <C-_> :help<CR>``` in init.vim file
2. Reload cfg and try to CTRL+/

**Expected behavior**
In neovim opens help page

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 LTSC
 - Neovide Version: 0.9.0
 - Neovim Version: 0.7.2

**Comment by MultisampledNight** [comment]
Thank you for reporting! I'm not sure if I'm understanding the issue correctly though. `<C-_>` literally maps <kbd>Ctrl</kbd> and <kbd>_</kbd> together, <kbd>/</kbd> is nowhere to be found in that sequence. Probably you've meant to map `<C-/>` instead?

If not, that sounds like a layout vs. printed character on keyboard mismap issue. What keyboard layout are you using and which one is printed on the physical keyboard?

**Comment by eriedaberrie** [comment]
@MultisampledNight I use exclusively Windows for Neovim like OP so I'm not sure about other platforms/terminal emulators but in both Windows Terminal and conhost I've found that the key combination ctrl+slash is captured by <C-_>, while neither <C-/> nor <C-_> seem to be able to capture it in Neovide.

**Comment by BestChinchilla** [comment]
@MultisampledNight ```<C-_>``` is maps to <kbd>CTRL</kbd>+<kbd>/</kbd>  
You can check it in neovim by typing ```/``` and after that press <kbd>CTRL</kbd>+<kbd>/</kbd> you would see symbol ```^_```
The problem is that neovide doesn't recognize the keyboard shortcut

Keyboard layout: Eng US

**Comment by MultisampledNight** [comment]
I see. Switching my layout to the US one and trying it out in nvim + alacritty on Arch Linux, `<C-_>` only fires upon <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>-</kbd>, _not_ upon <kbd>Ctrl</kbd> + <kbd>/</kbd>. Mapping `<C-/>` works on my system though. Which makes me think this is either a Windows-specific issue or my understanding of keyboard input is plainly wrong.

According to [the article about ASCII caret notation](https://en.wikipedia.org/wiki/Caret_notation#Use_in_software), <kbd>Ctrl</kbd> + <kbd>/</kbd> on the US layout is interpreted as... DEL, which is `^?`. I'm not sure how up-to-date that note is, which cases and which systems it applies to though.

**Comment by fredizzimo** [comment]
This should be fixed by #1899, it would be great if you can test that.

**Comment by TzeroOcne** [comment]
Hello, I'm still encounter this issue in neovide 0.15.2 version using windows 11 and neovim 0.10.4, can we reopen this or I need to open new issue?
