### ISSUE TITLE
Support Emojis floating window in Mac

### ISSUE THREAD

**Issue by alexventuraio** [neovide/neovide#1493]
I come from [MacVim](projects_2022_08_19) app and there I have the ability to press CTRL + CMD + space and I get the usual emojis window poping up to select any emoji and click on it to be written in the buffer file.

<img width="485" alt="Screen Shot 2022-08-19 at 18 05 17" src="https://user-images.githubusercontent.com/13169164/185718165-2a784190-cddf-4477-8d5b-16384d3d0997.png">

It would be good to have the same behavior but instead it writes the key combination:

<img width="378" alt="Screen Shot 2022-08-19 at 18 06 32" src="https://user-images.githubusercontent.com/13169164/185718162-7cf62189-1da3-4f03-b2b1-4ddc1c13c408.png">

**Additional context**
MacOS X 12.4

**Comment by bram-dingelstad** [comment]
Would love to take a stab at this. What would be a great place to start @Kethku?

**Comment by mgax** [comment]
First of all, `CTRL` + `CMD` + `space` is just one of the ways to open the emoji window, another would be the `🌐` key. The globe key does actually open the emoji window, but after selecting a character, it's not inserted.

I've poked around with winit (upstream) and found that this function actually receives the selected character: https://github.com/rust-windowing/winit/blob/f7a400ddf6a7822a1ac0cf80ca805dcf3298872e/src/platform_impl/macos/view.rs#L426.

**Comment by fredizzimo** [comment]
Is this fixed by the Winit update included in Neovide 0.11.0?

**Comment by sidequestboy** [comment]
I still experience this issue on neovide 0.11.0 installed via homebrew cask `brew install homebrew/cask/neovide`.

It still inserts "`<C-D-Space>`" when pressing Ctrl-Cmd-Space

**Comment by fredizzimo** [comment]
Does this work on Alacritty, which also uses Winit? Apparently not, https://github.com/alacritty/alacritty/issues/6164,  on the other hand it has been working before https://github.com/alacritty/alacritty/issues/467

I'm not sure how this is supposed to work, I was assuming it would use the IME support, which is used even for dead keys on macOS, but apparently not, since it should be enabled by default, and just work.

The other option is that it's some kind of special system shortcut, but the OS thinks that winit/neovide handles it, and therefore does not process it. I think that needs a Winit fix. 

In both of these cases I think we need a Winit fix for it, could someone create an issue there?

**Comment by wzhliang** [comment]
0.11.2 here and it's still a problem. Please fix this so that I can stay in neovide forever.

**Comment by fredizzimo** [comment]
This request should go to winit. Just like Alacritty, we don't want to make custom solutions like this https://github.com/alacritty/alacritty/pull/3561

**Comment by fredizzimo** [comment]
There's now an open issue on winit for this
* https://github.com/rust-windowing/winit/issues/3342

**Comment by fredizzimo** [comment]
Apparently there's a workaround that can be used if your keyboard has dead keys. Type a dead key first, and then the emoji selector can be used.

**Comment by chardskarth** [comment]
I'm curious with the workaround. How can I know if I have a dead key?

**Comment by fredizzimo** [comment]
If you don't know what a dead key is, then you probably don't have one in your layout. 
https://en.wikipedia.org/wiki/Dead_key

Perhaps you could use some plugin-based solution like this https://github.com/ziontee113/icon-picker.nvim

**Comment by 9mm** [comment]
@falcucci is this one on your radar at all? I use neovide for a lot of non-coding stuff, like markdown files and I definitely miss this feature

**Comment by ronisbr** [comment]
Also, when adding, for example, labels to plots, the emoji picker is very handy.

> Type a dead key first, and then the emoji selector can be used.

Btw, I have dead keys but it is not working.
