### ISSUE TITLE
Neovide hover popup overflows the window edge to the right/bottom and not staying within window boundaries

### ISSUE THREAD

**Issue by juhaku** [neovide/neovide#1641]
**Describe the bug**
When hovered over method / function / struct etc declaration the hover box overflows over the right screen edge when opened with neovide. But when same operation is performed with neovim using terminal or in this case KDE's konsole the hover will not overflow the screen edge but stays withing the window boundaries.

I am aware there was previously bug related it overflowing to the left, but did not find a issue related it bleeding to the right of the window.

**To Reproduce**
1. Open any file which has language support protocol enabled with support for hovering documentation. 
2. Either make window small enough (for example splitting) or make sure you have big enough hover documentation available.
3. Open hover e.g. hovering a function / method / struct / class etc. declaration.
4. See if the hover window stays withing the window (and within split window).

**Expected behavior**
The hover should stay within the window boundaries and not overflow to the right.

**Screenshots**
![image](https://user-images.githubusercontent.com/26358664/202572587-09d9ac13-b605-4b74-ba1b-fe3c6048b845.png)
![image](https://user-images.githubusercontent.com/26358664/202573288-175bce6e-d73b-4442-8853-f4a1adbbbb70.png)

**Desktop (please complete the following information):**
 - OS: Manjarjo KDE / Endeavour OS KDE / v. 5.26 ->
 - Neovide Version 0.10.3
 - Neovim Version 0.8.0 ->

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
Attached log files since the content would be too large to paste in this thread.
[neovide_r2022-11-18_00-39-32.log](https://github.com/neovide/neovide/files/10036250/neovide_r2022-11-18_00-39-32.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10036251/neovide_rCURRENT.log)

**Comment by juhaku** [comment]
It also overflows to the bottom as seen in latter image.
![image](https://user-images.githubusercontent.com/26358664/202877004-08152ccf-fcff-421a-8199-a990f3a7435f.png)
![image](https://user-images.githubusercontent.com/26358664/202876972-0d8ed9a6-8a1c-41ef-8589-dda4688aefc5.png)

**Comment by fredizzimo** [comment]
This is probably fixed by https://github.com/neovide/neovide/pull/1786

**Comment by juhaku** [comment]
@fredizzimo  Just tested with master branch and result is still the same.
![image](https://user-images.githubusercontent.com/26358664/229350967-d166ed6e-7ebb-4aa5-b61a-6d4b3e9d7625.png)

**Comment by fredizzimo** [comment]
This looks like a Neovim bug, according to the logs it does not report the correct position. I will report the bug on their issue tracker. It might be possible that we are expected to do the positioning ourselves, but let's see what the response is first.

I think it's this code that is the problem
https://github.com/neovim/neovim/blob/996dd36c77321ea91758b5996d152a2f37af99dd/src/nvim/window.c#L986-L1018

**Comment by fredizzimo** [comment]
This Neovim issue has been crated https://github.com/neovim/neovim/issues/24801

**Comment by fredizzimo** [comment]
This will be fixed by #2029. But it would still have been better for Neovim to deal with it.
