### ISSUE TITLE
Add option to don't store window geometry

### ISSUE THREAD

**Issue by damanis** [neovide/neovide#1753]
**Is your feature request related to a problem? Please describe.**
Window geometry stored in `neovide-settings.json` even then `let g:neovide_remember_window_size = v:false`.
As a result, neovide window always open on same place.
Now window dimensions properly calculated by font configuration, window position specified by window manager (in Linux), but restore geometry from `neovide-settings.json` override them.

**Describe the solution you'd like**
Just add configuration option to don't save and restore window geometry

**Comment by shaunsingh** [comment]
This should be fixed with https://github.com/neovide/neovide/pull/1119

**Comment by damanis** [comment]
The option `geometry` still does not exist, need to delete neovide-settings.json before run Neovide.
