### ISSUE TITLE
Window shadow is lost on MacOS after switching away using Mission Control

### ISSUE THREAD

**Issue by mgax** [neovide/neovide#1888]
**Describe the bug**
On MacOS, if I navigate away from Neovide using Mission Control, the window loses its shadow.

**To Reproduce**
1. Open Neovide.
2. Activate [Mission Control](https://support.apple.com/en-us/HT204100).
3. Select some other window than Neovide.
4. The Neovide window has no drop shadow.

**Expected behavior**
The window should retain its shadow as usual. Without the drop shadow it becomes difficult to distinguish overlapping Neovide windows because their backgrounds visually merge.

**Screenshots**
Normal drop shadow when Neovide is in the background:
<img width="744" alt="Screenshot 2023-06-04 at 14 59 20" src="https://github.com/neovide/neovide/assets/27617/a9738f3c-58ff-430f-b091-a28d6dc4a766">
Drop shadow is gone:
<img width="714" alt="Screenshot 2023-06-04 at 14 57 37" src="https://github.com/neovide/neovide/assets/27617/e1b4d3ae-e9f8-4aec-9c33-2829da3f27bb">

**Desktop (please complete the following information):**
 - OS: MacOS 13.4
 - Neovide Version: 0.10.4
 - Neovim Version: 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://gist.github.com/mgax/2afdc0575c2213ec88cebab44bc67ddb

**Additional context**
Background windows have a lighter drop shadow than the foreground window. Interestingly, when the Neovide window is brought back to the front, it has a normal shadow. If another window is selected, it loses its shadow completely again. I've only been able to reproduce the bug using Mission Control; switching applications using command-tab does not trigger it.

Disabling window transparency makes the bug go away:
```diff
diff --git a/src/window/mod.rs b/src/window/mod.rs
index b1f7ca5..511e52e 100644
--- a/src/window/mod.rs
+++ b/src/window/mod.rs
@@ -346,7 +346,7 @@ pub fn create_window() {
         .with_title("Neovide")
         .with_window_icon(Some(icon))
         .with_maximized(maximized)
-        .with_transparent(true);
+        .with_transparent(false);
 
     let frame_decoration = cmd_line_settings.frame;
 
```

**Comment by fredizzimo** [comment]
This looks like it might be a winit bug, could you try again with the latest master. We just merged this https://github.com/neovide/neovide/pull/1789 which updates winit.

**Comment by mgax** [comment]
The bug is still present on neovide main. I tried to reproduce it on winit main, and you're right, it's a winit bug. I'll make a bug report there.

**Comment by fredizzimo** [comment]
I have a potential fix for this here:
* https://github.com/neovide/neovide/pull/2562

It would be good if someone could test it.
