### ISSUE TITLE
White flash during Neovide startup on Microsoft Windows

### ISSUE THREAD

**Issue by harg** [neovide/neovide#2142]
**Describe the bug**
On Neovide Launch, an empty window with white background is displayed just before rendering the correct colorscheme background, causing an annoying white flash.

**To Reproduce**
1. Launch Neovide on Microsoft  Windows

**Expected behavior**
On Neovide Launch, display the neovide window with the colorscheme background (or black background)

**Desktop :**
 - OS: Microsoft Windows 10
 - Neovide latest version
 - Neovim latest version

**Comment by sid-6581** [comment]
I see that as well, I don't think the surface is being filled with anything before the window is drawn the first time. If nobody else fixes it, I have it on my list to look at when I get some free time.

**Comment by fredizzimo** [comment]
I forgot to comment about this issue, but I think it's mostly because this wint function does not use a single WinApi call to set the window state 

https://github.com/rust-windowing/winit/blob/17296e98783a19c2f0a552340682e3de2b863de8/src/platform_impl/windows/window_state.rs#L305-L434

So it's unable to for example resize the window and show it at the same time. If you just set the size, it's temporary shown then resized and hidden again, and if you show it, then it's temporarily shown with the wrong size. And then it's not a all sure that we happen to render anything between those actions. Especially when starting a maximised window. 

The winapi function `SetWindowPos` can do everything at once, so there's no reason for the function to be written that way.

**Comment by fredizzimo** [comment]
I forgot to add:
I don't remember what the issue was that prevented me from doing this, but I think it's resolved now with the way we calculate the window size before creating the window. I think it would be better to create the window at the time it's shown, rather than creating it as hidden, since I think that codepath is atomic. 

Winit also has some plans for only allowing creation of windows inside the event loop, so that would support that flow a lot better. And there was also some issue, that I don't remember right now, that would be solved, or solvable by moving the creation inside the loop. So those would be other good reasons for moving the creation.

**Comment by fredizzimo** [comment]
The issue was fixed in some of the 0.12.x versions of Neovide.

**Comment by sid-6581** [comment]
@fredizzimo I don't think this should be closed yet, I'm still seeing the same issue with both Direct3D and OpenGL rendering on Windows 11.

**Comment by fredizzimo** [comment]
Ok, I will re-open. I see some minor flashing when launching in full screen mode, but not nearly as bad as it was when the issue was reported.

I'm not sure if it can be totally fixed on our side, even when we move the window creation to the event loop, and only create it when it's shown. Winit still uses multiple API calls to configure the window here and it should be possible to do atomically
https://github.com/rust-windowing/winit/blob/ab33fb8eda45f9a23587465d787a70a309c67ec4/src/platform_impl/windows/window_state.rs#L316-L425

**Comment by fredizzimo** [comment]
I have a potential fix for this here:
* https://github.com/neovide/neovide/issues/915

It would be good if someone could test it.

**Comment by yavorski** [comment]
I will give it shot shortly.

**Comment by fredizzimo** [comment]
@yavorski, that might be the same issue actually.

**Comment by yavorski** [comment]
Summary:

* `v0.12.2` - open animation has `white` background color; `columns` are NOT set correctly after maximizition;
* `v0.13.0` - open animation has `black` background color; `columns` Ok.
* `v0.13.0 + this.fix` - open animation has `transparent` background color now; Frames/Borders of the application are visible during startup with transparent rectangle inside as content now. `columns` Ok.
