### ISSUE TITLE
Bold and italic not rendered on MacOS

### ISSUE THREAD

**Issue by sebszyller** [neovide/neovide#2377]
**Describe the bug**
Bold and italic fonts are not rendered.

**To Reproduce**
Open any text file where some parts should be rendered in bold or italic.

**Expected behavior**
Text with bold, italic or bold_italic properties should be rendered as such (work in neovim).

**Screenshots**
<img width="1528" alt="Screenshot 2024-02-22 at 21 21 08" src="https://github.com/neovide/neovide/assets/11989990/09f5a6be-8d51-45fc-bb36-06492056c1d0">

Neovim (left) renders italics correctly; Neovide (right) doesn't. Same for bold.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14.2.1]
 - Neovide Version [e.g. 0.12.2]
 - Neovim Version [e.g. 0.9.5]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14378629/neovide_rCURRENT.log)

**Additional context**
I'm using vanilla Monaco in the screenshot but the same holds for other built-in fonts, as well as the Nerd-Font-patched variant.
AFAIK, treesitter exposes information to the theme which applies styling to the text element (colour and other styling). Then this information is sent to neovim and up to the terminal (iTerm2) or to neovide to render.

Looking at the log file, it *seems* to me that something is lost (lines 1449-1454).

**Comment by fredizzimo** [comment]
I'm fairly sure that this is fixed on main with this pr
* https://github.com/neovide/neovide/pull/2354

Are you able to try that?

**Comment by sebszyller** [comment]
I've just built it from main, and it isn't fixed. Here's a log from that.
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14379392/neovide_rCURRENT.log)

**Comment by sebszyller** [comment]
Okay, thanks for the info. Let's close this then.
But to get this straight, iTerm2, VSCode and others are rendering faux bold and italic for Monaco then?

**Comment by fredizzimo** [comment]
Yes, I think they do. And I think we should as well, but we have a few higher priority issues first.

So, let's leave the issue open until it's implemented.

**Comment by yavorski** [comment]
There is an issue with current version `v13.3.0` that it is not rendering `bold italic`, but it is fixed in latest `main` branch.
Left is `v13.3.0` version, right is current build from `main` branch. Take a look at the comments to notice the difference.

![neovide-13 3 0-vs-master](https://github.com/user-attachments/assets/b296e053-2a30-49f8-889d-db8823212d02)

**Comment by fredizzimo** [comment]
@yavorski, are you sure you were on 0.13.3, your bug matches the one we had in 0.13.2 and was fixed in 0.13.3 here
* https://github.com/neovide/neovide/pull/2710

This bug is about faux/synthetic bold and italic and only happens with fonts that don't have bold and italic style by themselves like the `Monaco` font of the original issue. Jetbrains has both italic and bold styles, and even the `ExtraBoldItalic` style.

**Comment by yavorski** [comment]
Hi, in my 0.13.3 version installed from arch with pacman the `bold italic` is not rendering correctly ( I have all the fonts ).

Reinstalling neovide just to be sure ...

![image](https://github.com/user-attachments/assets/90cdb217-417a-4a85-b3c6-dd2e59abdf4e)

This is my neovide config: 

```toml
[font]
size = 11.25
hinting = "full"
edging = "antialias"
allow_float_size = true

[[font.normal]]
style = "Bold"
family = "Intel One Mono"

[[font.bold]]
style = "Bold"

[[font.italic]]
slant = "Italic"
style = "Bold Italic"

[[font.bold_italic]]
slant = "Italic"
style = "Bold Italic"
```

When I build neovide from source with latest commit fonts are rendered correctly. You can see previous screenshot for the difference in rendering.

Let me know If you need more logs or sth.

**Comment by fredizzimo** [comment]
Hm.. I'm starting to wonder if there's something wrong with the 0.13.3-3 package on Arch Linux also based on this message https://github.com/neovide/neovide/issues/2786#issuecomment-2366808106. I currently have 0.13.3-2, but I will upgrade to 0.13.3-3 later today to check myself. 

But here's one check you can do, inside Neovide type `:echo g:neovide_version`, that should say `0.13.3`.

How long have you had this problem? `0.13.3-3` was released a few days ago, so if you have had it longer, we can rule that out.

**Comment by yavorski** [comment]
Hmm, not sure, but I guess it is since 0.13.3, previously I didn't noticed this issue, and I was heavily using neovide since start of the year. g:neovide_version is printing the correct version - and on this screenshot comments are not bold and they should be.

![image](https://github.com/user-attachments/assets/da92c05c-6e8e-4263-92b7-5c557e338960)

**Comment by yavorski** [comment]
Sorry! I was rebuilding from my fork, which was 42 commits behind... Now after syncing with upstream and rebuild again with `cargo build --release` the problem is actually not fixed. It is not rendering `bold italic`.

**Comment by fredizzimo** [comment]
Ok, I will look at this soon, but can you open a new issue, so that we can track this separately? As far as I can see, both `Intel One Mono` and `JetBrains Mono NL` supports real bold and italics, so the issue is different.

I suspect it has something do with fallback fonts specifying their own styles.

**Comment by fredizzimo** [comment]
@yavorski, I created the bug report https://github.com/neovide/neovide/issues/2807
