### ISSUE TITLE
Pasting in search mode will not trigger rendering

### ISSUE THREAD

**Issue by LavaCxx** [neovide/neovide#2386]
I bound the `cmd + v` key according to this [comment](https://github.com/neovide/neovide/issues/1263#issuecomment-1100895622) in a previous issue.
However, when using this shortcut key in search mode, the pasted content will not be rendered in the input box until other keys are pressed.

**To Reproduce**
1. press `/`
2. press `cmd + v`

**Expected behavior**
Render the pasted content.

**Screenshots**

![gif](https://github.com/neovide/neovide/assets/48022591/7c9db50c-17b5-475f-97c6-ff2499387428)

**Desktop (please complete the following information):**
 - OS:  macOS 14.2.1
 - Neovide Version: 0.12.2
 - Neovim Version: v0.10.0-dev-2427+geb4783fb6

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        SuperLeft,
    ),
    logical_key: Named(
        Super,
    ),
    text: None,
    location: Left,
    state: Pressed,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: None,
        key_without_modifiers: Named(
            Super,
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Modifiers { state: ModifiersState(SUPER), pressed_mods: ModifiersKeys(LSUPER) }
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::editor] Image flushed
TRACE [neovide::editor] send_batch
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        KeyV,
    ),
    logical_key: Character(
        "v",
    ),
    text: Some(
        "v",
    ),
    location: Standard,
    state: Pressed,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: Some(
            "v",
        ),
        key_without_modifiers: Character(
            "v",
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Key pressed <D-v> ModifiersState(SUPER)
TRACE [neovide::channel_utils] UICommand Serial(Keyboard("<D-v>"))
TRACE [neovide::bridge::ui_commands] In Serial Command
TRACE [neovide::bridge::ui_commands] Keyboard Input Sent: <D-v>
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovim_handler BusyStart
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::editor] Cursor off
TRACE [neovide::editor] Image flushed
TRACE [neovide::editor] send_batch
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovim_handler BusyStop
TRACE [neovide::channel_utils] neovim_handler WindowPosition { grid: 2, start_row: 0, start_column: 0, width: 192, height: 38 }
TRACE [neovide::editor] Cursor on
TRACE [neovide::channel_utils] neovim_handler WindowFloatPosition { grid: 13, anchor: NorthWest, anchor_grid: 2, anchor_row: 1.0, anchor_column: 6.0, focusable: false, sort_order: Some(20) }
TRACE [neovide::channel_utils] neovim_handler WindowFloatPosition { grid: 12, anchor: NorthWest, anchor_grid: 2, anchor_row: 1.0, anchor_column: 0.0, focusable: false, sort_order: Some(20) }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 1, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "8", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 2, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "7", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 3, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 4, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 5, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 6, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 7, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "2", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 8, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: None }, GridLineCell { text: "1", highlight_id: Some(1871), repeat: Some(2) }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 9, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "0", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 10, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: Some(2) }, GridLineCell { text: "9", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 11, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: Some(2) }, GridLineCell { text: "8", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 12, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: Some(2) }, GridLineCell { text: "7", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 13, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: Some(2) }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 14, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: Some(2) }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 15, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1871), repeat: Some(2) }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 16, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1232), repeat: Some(2) }, GridLineCell { text: "3", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 17, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1232), repeat: Some(2) }, GridLineCell { text: "2", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 18, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1232), repeat: Some(2) }, GridLineCell { text: "1", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 20, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1232), repeat: Some(2) }, GridLineCell { text: "1", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 21, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1232), repeat: Some(2) }, GridLineCell { text: "2", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 22, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: Some(2) }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 23, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: Some(2) }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 24, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: Some(2) }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 25, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: Some(2) }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 26, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: Some(2) }, GridLineCell { text: "7", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 27, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: Some(2) }, GridLineCell { text: "8", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 28, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: Some(2) }, GridLineCell { text: "9", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 29, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "0", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 30, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: None }, GridLineCell { text: "1", highlight_id: Some(1872), repeat: Some(2) }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 31, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "2", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 32, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 33, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 34, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 35, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 36, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "7", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 37, column_start: 2, cells: [GridLineCell { text: " ", highlight_id: Some(1872), repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: "8", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler WindowViewport { grid: 2, top_line: 129.0, bottom_line: 167.0, current_line: 147.0, current_column: 22.0, line_count: Some(371.0), scroll_delta: Some(0.0) }
TRACE [neovide::channel_utils] neovim_handler WindowViewport { grid: 145, top_line: 0.0, bottom_line: 1.0, current_line: 0.0, current_column: 4.0, line_count: Some(1.0), scroll_delta: Some(0.0) }
TRACE [neovide::channel_utils] neovim_handler WindowViewport { grid: 144, top_line: 0.0, bottom_line: 1.0, current_line: 0.0, current_column: 0.0, line_count: Some(1.0), scroll_delta: Some(0.0) }
TRACE [neovide::channel_utils] neovim_handler WindowViewport { grid: 13, top_line: 0.0, bottom_line: 3.0, current_line: 0.0, current_column: 0.0, line_count: Some(3.0), scroll_delta: Some(0.0) }
TRACE [neovide::channel_utils] neovim_handler WindowViewport { grid: 12, top_line: 0.0, bottom_line: 3.0, current_line: 0.0, current_column: 0.0, line_count: Some(3.0), scroll_delta: Some(0.0) }
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::editor] Image flushed
TRACE [neovide::editor] send_batch
TRACE [neovide::renderer::rendered_window] Handling Viewport 2
TRACE [neovide::renderer::rendered_window] Handling Viewport 145
TRACE [neovide::renderer::rendered_window] Handling Viewport 144
TRACE [neovide::renderer::rendered_window] Handling Viewport 13
TRACE [neovide::renderer::rendered_window] Handling Viewport 12
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        KeyV,
    ),
    logical_key: Character(
        "v",
    ),
    text: None,
    location: Standard,
    state: Released,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: Some(
            "v",
        ),
        key_without_modifiers: Character(
            "v",
        ),
    },
}
TRACE [neovide::window::keyboard_manager] KeyEvent {
    physical_key: Code(
        SuperLeft,
    ),
    logical_key: Named(
        Super,
    ),
    text: None,
    location: Left,
    state: Released,
    repeat: false,
    platform_specific: KeyEventExtra {
        text_with_all_modifiers: None,
        key_without_modifiers: Named(
            Super,
        ),
    },
}
TRACE [neovide::window::keyboard_manager] Modifiers { state: ModifiersState(0x0), pressed_mods: ModifiersKeys(0x0) }
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::editor] Image flushed
TRACE [neovide::editor] send_batch
TRACE [neovide::channel_utils] UICommand Parallel(FocusLost)
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovim_handler WindowFloatPosition { grid: 13, anchor: NorthWest, anchor_grid: 2, anchor_row: 1.0, anchor_column: 6.0, focusable: false, sort_order: Some(20) }
TRACE [neovide::channel_utils] neovim_handler WindowFloatPosition { grid: 12, anchor: NorthWest, anchor_grid: 2, anchor_row: 1.0, anchor_column: 0.0, focusable: false, sort_order: Some(20) }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 1, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: "0", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 2, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 3, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: "2", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 4, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: Some(1491), repeat: Some(2) }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 5, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 6, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 7, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 8, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: "7", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 9, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: "8", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 10, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: "9", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 11, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: "0", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 12, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 13, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: "2", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 14, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 15, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "4", highlight_id: Some(1491), repeat: Some(2) }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 16, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1232), repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 17, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1232), repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 18, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1232), repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: "7", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 20, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1232), repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: "9", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 21, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1232), repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: "0", highlight_id: None, repeat: None }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 22, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 23, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: "2", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 24, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 25, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 26, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "5", highlight_id: Some(1491), repeat: Some(2) }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 27, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 28, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: "7", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 29, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: "8", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 30, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: "9", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 31, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: "0", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 32, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 33, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: "2", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 34, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: "3", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 35, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: "4", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 36, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "6", highlight_id: None, repeat: None }, GridLineCell { text: "5", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler GridLine { grid: 2, row: 37, column_start: 2, cells: [GridLineCell { text: "1", highlight_id: Some(1491), repeat: None }, GridLineCell { text: "6", highlight_id: Some(1491), repeat: Some(2) }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: Some(0), repeat: Some(0) }] }
TRACE [neovide::channel_utils] neovim_handler WindowViewport { grid: 2, top_line: 129.0, bottom_line: 167.0, current_line: 147.0, current_column: 22.0, line_count: Some(371.0), scroll_delta: Some(0.0) }
TRACE [neovide::channel_utils] neovim_handler Flush
TRACE [neovide::editor] Image flushed
TRACE [neovide::editor] send_batch
TRACE [neovide::renderer::rendered_window] Handling Viewport 2
```
**Additional context**

**Comment by fredizzimo** [comment]
This looks like a Neovim bug, it just does not send us the information. I will report it a bit later when I have time.

For now you can set `silent=false` as a workaround.

**Comment by fredizzimo** [comment]
This was most likely fixed with https://github.com/neovim/neovim/pull/30576. Are you able to test with the latest Neovim nightly? I don't have access to a computer right now myself.

**Comment by LavaCxx** [comment]
> This was most likely fixed with [neovim/neovim#30576](https://github.com/neovim/neovim/pull/30576). Are you able to test with the latest Neovim nightly? I don't have access to a computer right now myself.

Due to work reasons, I haven't used neovim for a long time. But it seems to be working fine now, so I'll go ahead and close this issue.

**Comment by eaoliver** [comment]
The bug as described is still present in 0.14.1.  I can reproduce it consistency with the following keymapping:
```lua
vim.keymap.set('c', '<D-v>', '<C-R>+', { silent = false }) -- Paste command mode
```

**Comment by vsuharnikov** [comment]
It works with my config:
```lua
vim.opt.clipboard = "unnamedplus"

if vim.g.neovide then
  vim.g.neovide_no_idle = true
  vim.g.neovide_confirm_quit = true
  vim.g.neovide_macos_simple_fullscreen = true
  vim.g.neovide_input_macos_option_key_is_meta = "only_left"
  vim.g.neovide_cursor_animation_length = 0.150
  vim.g.neovide_cursor_short_animation_length = 0.04
  vim.g.neovide_cursor_animate_command_line = true

  vim.keymap.set({ "n", "v", "s", "x", "o", "i", "l", "c", "t" }, "<D-v>", function()
    vim.api.nvim_paste(vim.fn.getreg("+"), true, -1)
  end, { noremap = true, silent = false, desc = "paste from system clipboard" })
else -- <---------------- DOESN'T WORK IF COMMANDS BELOW OUTSIDE "else"
  -- Allow clipboard copy paste in neovim
  vim.api.nvim_set_keymap("", "<D-v>", "+p<CR>", { noremap = true, silent = true })
  vim.api.nvim_set_keymap("!", "<D-v>", "<C-R>+", { noremap = true, silent = true })
  vim.api.nvim_set_keymap("t", "<D-v>", "<C-R>+", { noremap = true, silent = true })
  vim.api.nvim_set_keymap("v", "<D-v>", "<C-R>+", { noremap = true, silent = true })
end
```
