### ISSUE TITLE
Window transparency is wrong for telescope windows. 

### ISSUE THREAD

**Issue by lunik1** [neovide/neovide#2686]
**Describe the bug**
Window transparency is wrong for telescope windows. 

**To Reproduce**
1. Set `winblend`
2. Open a telescope window

**Expected behavior**
Telescope popup transparency should match those of other windows, as it does in the terminal

**Screenshots**
Terminal:
![image](https://github.com/neovide/neovide/assets/13547699/980d635a-8ffb-47d0-b050-e99b640e4edc)

Neovide:
![image](https://github.com/neovide/neovide/assets/13547699/13a0ee4b-1dcb-4e3a-8c74-97fceebc81d3)

**Desktop (please complete the following information):**
 - OS: NixOS unstable
 - Neovide Version 0.13.1
 - Neovim Version: 0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

https://gist.github.com/lunik1/10a1234887d6bc2098cf732127fd92af

**Additional context**
[gruvbox colorscheme](https://github.com/ellisonleao/gruvbox.nvim)

**Comment by fredizzimo** [comment]
This should already be fixed on main with:
* https://github.com/neovide/neovide/pull/2612

**Comment by lunik1** [comment]
Ah good to know. I'll reopen if I still see this with the next release.
