### ISSUE TITLE
Neovide doesn't start on windows

### ISSUE THREAD

**Issue by Nishith-Savla** [neovide/neovide#574]
I've installed the stable release of neovide.exe from the releases page. I also have neovim(nvim) added to the path.
But whenever I try to open it neither opens nor it displays any error.

Tried using the --log as well as the --clean option but didn't get any output

```
OS: Windows 10 Pro Version 20H2
GPU: Integrated (Intel HD Graphics 4600)
```

**Comment by PyGamer0** [comment]
The `--log` doesn't create a file??

**Comment by Nishith-Savla** [comment]
Oh sorry, It did. Let me ad it here
```log
INFO [neovide::bridge] Close watcher started
INFO [neovide::bridge] Neovim process attached
INFO [neovide::bridge] UiCommand processor started
```
That's it

**Comment by quintik** [comment]
Hello! I was having the same issue. I installed `neovide.exe` from the releases page (0.7.0) and tried to run it but nothing happened. I ran it with both `--log` and `--clean`. This is what the logs gave:
```
$ bat neovide_rCURRENT.log
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: neovide_rCURRENT.log
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include em
       │ bed-fonts feature
   2   │ WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include e
       │ mbed-fonts feature
   3   │ WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include em
       │ bed-fonts feature
   4   │ WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include e
       │ mbed-fonts feature
   5   │ WARN [neovide::renderer::fonts::font_loader] Tried to load Extra Symbols.otf from assets but build didn't include em
       │ bed-fonts feature
   6   │ WARN [neovide::renderer::fonts::font_loader] Tried to load Missing Glyphs.otf from assets but build didn't include e
       │ mbed-fonts feature
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I also installed `0.6.0` and ran it with `--log` and `--clean`. This is what the logs gave:
```
$ bat neovide1_rCURRENT.log
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: neovide1_rCURRENT.log
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ INFO [neovide::bridge] Close watcher started
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

Also, I am curious, how is the size of the binary so different in each release? ~30mb for 0.7.0, ~9mb for 0.6.0 and ~50mb for 0.5.0!

**Comment by Kethku** [comment]
Re startup. Can you try the opengl branch?
Re size. in 0.5.0 we embedded font files which caused people to be frustrated with the size ofthe exe. In 0.6 we removed those by default (although I think you can still add them with a feature flag.) in 0.7 we changed dependencies pretty significantly. I'm not sure exactly what is causing that extra size, but its possible that some dependency is pulling in a lot of extra data.

**Comment by rsrini7** [comment]
My windows neovide --clean --log

ERROR [neovide::error_handling] Could not locate or start the neovim process: The system cannot find the file specified. (os error 2)
INFO [neovide::window] window created
INFO [neovide::window] renderer created
INFO [neovide::window] Starting window event loop
TRACE [neovide::editor::grid] Editor resized
TRACE [neovide::redraw_scheduler] Next frame queued
DEBUG [neovide::window] Render Triggered
TRACE [neovide::renderer] Rendering
TRACE [neovide::editor] Draw commands sent
.......
DEBUG [neovide::window] Render Triggered
TRACE [neovide::window] KeyDown Received: Space
TRACE [neovide::window] Keyboard Input Received:  
TRACE [neovide::bridge] UiCommand queued: Keyboard(" ")
ERROR [neovide::error_handling] Could not send UI command from the window system to the neovim process.: channel closed

**Comment by Kethku** [comment]
Sounds like neovide can't find the neovim process. Is it on the path?

**Comment by Kethku** [comment]
Its looking for nvim.exe

**Comment by rsrini7** [comment]
Yes. Used Scoop to install neovide and added manually C:\SCOOP\apps\neovide\0.5.0 to PATH. But still same issue.

**Comment by Kethku** [comment]
note: neovide is not the same as neovim. nvim.exe must also be on the path

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you continue to see this issue.

**Comment by Nishith-Savla** [comment]
It still doesn't work and now when I use `--log` it creates a log file but its empty.

**Comment by jpambrun** [comment]
Building from master using GH Actions, I also  get nothing on stdout and can't find any log file.

``` bash
$ nvim --version
NVIM v0.5.0
[...]

$ ./neovide.exe --clean --log

$ ls
neovide.exe
```

**Comment by jpambrun** [comment]
I get a bit further with this build:
https://github.com/neovide/neovide/actions/runs/1088631240

The window briefly opens and closes and I can see the log file. Some stdout logging would be nice.

**Comment by Kethku** [comment]
Any chance either of you are using an amd gpu?

**Comment by jpambrun** [comment]
I am on AMD. I will keep an eye on https://github.com/neovide/neovide/issues/907.

**Comment by Kethku** [comment]
Closing in favor of the fix in #907. Please reopen if the issue persists though

**Comment by VimWei** [comment]
Neovide doesn't launch under windows 10 pro 19045.4412

**Comment by fredizzimo** [comment]
@VimWei, see this issue
*https://github.com/neovide/neovide/issues/2556

You can work around it with `neovide --opengl` for now
