### ISSUE TITLE
Natural scrolling not enforced for horizontal scrolling

### ISSUE THREAD

**Issue by sudormrfbin** [neovide/neovide#582]
There seems to be a difference in how scrolling works for horizontal vs vertical mode - vertical scrolling follows natural scrolling (moving the finger down scrolls up and vice versa) but horizontal scrolling follows the normal method (moving the finger right scrolls right instead of left).

### Reference

- Horizontal scrolling added to neovim in https://github.com/neovim/neovim/pull/3450.
- Apparently neovim scrolls naturally by default but if natural scrolling is enabled system wide then the effect is inverted - https://github.com/rogual/neovim-dot-app/issues/94#issuecomment-214572405

**Comment by Kethku** [comment]
Does this happen in console vim?

**Comment by Kethku** [comment]
I'm very suspicious this is an upstream issue.

**Comment by gokulsoumya** [comment]
It doesn't work at all in console neovim, tried on alacritty and xterm.

**Comment by Kethku** [comment]
Could you try on another gui like fvim/goneovim/neovim-qt? Without confirmation that they have a similar issue, it will be hard to make the case that its upstream.

**Comment by gokulsoumya** [comment]
I tried it on neovim-qt and it works as expected. I found a PR which "flips horizontal scroll direction to match other applications", https://github.com/equalsraf/neovim-qt/pull/273 and in the diff the directions are [simply inverted](https://github.com/equalsraf/neovim-qt/pull/273/files#diff-fc9f243598d80ce44e1f1bbbd7945877805836b89731eb29764463f18135d93aR704).

**Comment by Kethku** [comment]
Interesting. If you disable natural scrolling at the os level does horizontal scrolling also flip?

**Comment by gokulsoumya** [comment]
Yeah it does flip and now neovide has natural scroll in horizontal and normal scroll in vertical (neovim-qt has normal scroll now for both horizontal and vertical).

**Comment by shaunsingh** [comment]
I swapped the directions as Neovim-qt does and it works as expected now.

**Comment by LilMonk** [comment]
Does horizontal scrolling works in alacritty? I know this isn't the place to ask but I need the horizontal scrolling to work in terminal neovim.

**Comment by Kethku** [comment]
@shaunsingh I'm not tracking this properly. Is this fixed now that your PR merged?

**Comment by shaunsingh** [comment]
Yup, I think its safe to close the issue

**Comment by Saafo** [comment]
It's quite strange that this issue still exist in the latest release 0.11.1

**Comment by fredizzimo** [comment]
I have not verified it myself but based on @Saafo's report I'm re-opening the issue as there seem to be a regression.

**Comment by alexventuraio** [comment]
> It's quite strange that this issue still exist in the latest release 0.11.1

Same here, scrolling does feel weird in the last 0.11.1 release!

**Comment by alex35mil** [comment]
Same. Horizontal scroll is flipped in my Neovide. In all other apps, it works as it should. Vertical scroll works as expected.

**Comment by Quicksilver151** [comment]
i guess ill rollback a version

**Comment by fredizzimo** [comment]
Winit 0.27.0 fixed the scroll direction https://github.com/rust-windowing/winit/releases/tag/v0.27.0, so on our side it should just be a matter of switching it back as expected here https://github.com/neovide/neovide/blob/598f7779a404b729de33d748780e5be0de0197d5/src/window/mouse_manager.rs#L284

But I don’t have a touchpad setup to test on, so it’s better if someone who has makes the change and send a PR.

**Comment by fredizzimo** [comment]
Fixed by #2021
