### ISSUE TITLE
Receiving key signals that should not be received

### ISSUE THREAD

**Issue by Empathy117** [neovide/neovide#826]
When using `alt + tab` or `win + tab` to switch window it just type the tab to the file.
I think it should ignore key combinations.

**Comment by PyGamer0** [comment]
which version of neovide?

**Comment by Empathy117** [comment]
> which version of neovide?

0.7.0 on linux

**Comment by Empathy117** [comment]
![Peek 2021-07-14 22-05](https://user-images.githubusercontent.com/60363116/125636700-f0c133cb-f488-4257-813c-bb2e6d68fe21.gif)

And this what happen, I'm using Win + 1 to Switch to window 1 and use Win + tab to Switch back ...etc

**Comment by PyGamer0** [comment]
are you on main or using releases? i think this is foxed on main

**Comment by Empathy117** [comment]
> are you on main or using releases? i think this is fixed on main

Yes, I'm using on AUR pakcage before, and I build from source code from main branch now, but it still matter....

**Comment by masmullin2000** [comment]
On Arch Linux running AUR neovide-git (updated today, July 15th), I also experiencing something like this

Rather than receiving key signals upon entering the window, I experience key signals once I start typing. (the <D-char>... eg I type j and receive a <D-j>).

I should also note that my init.vim does not seem to be loaded once I enter the window.

I can fix by mouse clicking the neovide window and everything is back to normal.

This issue is very easy for me to reproduce, but very difficult to describe.  Let me know if I can assist.

**Comment by Kethku** [comment]
Could folks try main? I believe this has been fixed for real now

**Comment by mimullin-bbry** [comment]
It's not fixed for me.  Neovide recompiled for me this morning (august 2nd, 2021).

Note: I am running gnome 40 with pop-shell extension.

I do not know how to capture proper logs for this issue.  Let me know how I can help please.
