### ISSUE TITLE
panic on bg (Linux)

### ISSUE THREAD

**Issue by adsick** [neovide/neovide#831]
**Describe the bug**
Crashes when trying to run ```bg``` neovide (running ```neovide &``` works tho)

**To Reproduce**
1. run neovide
2. Ctrl+Z in the terminal
3. ```bg```
4. happy panic

**Expected behavior**
neovide normally runs in the background

**Screenshots**
![image](https://user-images.githubusercontent.com/24528839/126033883-2f41fcba-ebee-4dce-8580-5c8b9151f306.png)

**Desktop (please complete the following information):**
- Pop!_OS 21.04
 - Neovide Version [e.g. 0.7.0]
 - Neovim Version [e.g. 0.6.0]

**Comment by NrdyBhu1** [comment]
I was facing this exact issue on my linux pc
`Ubuntu 20.04`, but then I was able to resolve it when I compiled neovide my self and remove snap store's neovide

**Comment by leon332157** [comment]
Same issue here, could be a snap store issue. Maybe adding --classic will help?

**Comment by NrdyBhu1** [comment]
@leon332157 that doesn't seem to work
![2021-08-10_09-21](https://user-images.githubusercontent.com/61649925/128805684-9bfabc0a-e459-435a-82df-4e1400411e71.png)
![2021-08-10_09-22](https://user-images.githubusercontent.com/61649925/128805762-4ff2d50a-1cb4-432f-9b79-cd4517376530.png)

**Comment by j4qfrost** [comment]
I updated the snap just now, maybe it was fixed in the latest commit. Let me know.

**Comment by NrdyBhu1** [comment]
@j4qfrost, the snap version still doesn't work after updating, the only one that works is the one that i compiled myself

**Comment by j4qfrost** [comment]
@NrdyBhu1 then it's probably a configuration issue with the snap. I'll try to find some time to fix it this week, though I might not be able to find the problem if my system isn't configured the same as yours.

**Comment by leon332157** [comment]
Is it possible to allow for `--classic` with the snap package? What I meant by the last comment is allowing for --classic, which removes the sandbox and might help.

**Comment by j4qfrost** [comment]
I'll look into that. Sounds like it would solve the issue. @leon332157 Sorry my snap knowledge is limited.

**Comment by leon332157** [comment]
We can change [this](https://github.com/neovide/neovide/blob/725f12cafd4a26babd0d6bbcbca9a99c181991ac/snap/snapcraft.yaml#L10) line to change the confinement. See [here](https://snapcraft.io/docs/snap-confinement)

**Comment by NrdyBhu1** [comment]
> @NrdyBhu1 then it's probably a configuration issue with the snap. I'll try to find some time to fix it this week, though I might not be able to find the problem if my system isn't configured the same as yours.

I use Ubuntu 20.04, I dunno what else can I mention under configuration.
![Screenshot from 2021-08-11 08-50-45](https://user-images.githubusercontent.com/61649925/128964473-e0f18f46-15ee-4941-b5fc-c1bf8ca2c1da.png)

**Comment by Kethku** [comment]
I'm confident this is fixed as this issue is stale
