### ISSUE TITLE
Cursor jumps to command line when navigating through searches

### ISSUE THREAD

**Issue by comiluv** [neovide/neovide#903]
**Describe the bug**
After searching for a text in neovide if a user inputs "n" key to move to next search, the cursor is misplaced to the command line

**To Reproduce**
1. Search for a text ```/errroor```
2. Press "n" key to move to next search result

**Expected behavior**
The cursor is placed where the next search result is located.

**Screenshots**
![GIF 2021-08-17 오전 10-30-46](https://user-images.githubusercontent.com/19642705/129649482-2dedebf1-a9fb-42ae-9399-88a92cd0ec4f.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10/21H1 19043.1165
 - Neovide Version Neovide version: 0.8.0
 - Neovim Version NVIM v0.6.0-dev+116-g35041432b

**Please run `neovide --log` and paste the contents of the `.log` file here:**
https://drive.google.com/file/d/1mO65u4mdVx0IfXp6a6nefClLksMI8KI2/view?usp=sharing

**Additional context**

**Comment by Kethku** [comment]
Again, do you have lazyredraw enabled?

**Comment by comiluv** [comment]
> Again, do you have lazyredraw enabled?

no

**Comment by kuba-gaj** [comment]
Same issue, lazy redraw disabled

**Comment by Marskey** [comment]
same

**Comment by Marskey** [comment]
it seems is the nvim cause the issue

**Comment by Kethku** [comment]
Closing as I think this is fixed.

**Comment by Asheq** [comment]
This is not fixed, but it is a duplicate of #1665 so we can leave this closed and keep that one open.
