### ISSUE TITLE
First Ctrl key miss captured on linux when locate the pointer is enabled.

### ISSUE THREAD

**Issue by songww** [neovide/neovide#951]
**Describe the bug**

**To Reproduce**
1. enable locate the pointer (That will show position of pointer when the Control key is pressed
2. If Ctrl + SomeKey pressed, neovide only got `FocusLost.
3. Do not release Ctrl, press SomeKey can handle correctly.

**Desktop (please complete the following information):**
 - OS: Debian sid
 - Neovide Version: Head
 - Neovim Version: Head
 

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7149614/neovide_rCURRENT.log)

**Comment by rti** [comment]
I was able to reproduce the bug on Gnome/X11 40.4.0.

Which desktop environment are you running? Is it on X11 or Wayland?

**Comment by rti** [comment]
I just did some experimental changes which fix the issue for me. Would be curious if it fixes the issue for you as well.

If you want to give it a try, you find the branch here https://github.com/rti/neovide. It is called `fix-gnome-de-function-focus-loss-handling`.

**Comment by songww** [comment]
> I was able to reproduce the bug on Gnome/X11 40.4.0.
> 
> Which desktop environment are you running? Is it on X11 or Wayland?

Gnome/X11 3.38 and 40

**Comment by Kethku** [comment]
@rti I don't remember. Did this get merged in a PR? Thanks so much for investigating

**Comment by Kethku** [comment]
Ah I see in the other PR that we are waiting on Moroider. Do you think I should just modify my keyboard PR combination fork to target your branch?

**Comment by rti** [comment]
@Kethku It is actually about two issues. 

The PR waiting on Moroider is https://github.com/maroider/winit/pull/1 which fixes the meta modifier key state related issues on Gnome/X11, discussed in #942.

This issue here is a bit different, though, also related to weird Gnome focus behavior.

I am not planning to maintain a winit fork on my Github, so, if it is OK with you, I'd just provide the changes to your winit fork via PRs.

A PR fixing #942 is already opened for you. https://github.com/Kethku/winit/pull/1
I will open a second one fixing the CTRL key issue reported by the OP.

**Comment by rti** [comment]
PR for this issue is ready https://github.com/Kethku/winit/pull/2

**Comment by rti** [comment]
@Kethku Sorry, I forgot. To actually fix this issue, the winit change was not enough. I also changed https://github.com/neovide/neovide/blob/main/src/window/window_wrapper/keyboard_manager.rs#L42 to `false`. But unfortunately I do not understand why this is there at all.

**Comment by last-partizan** [comment]
@songww please, check out this branch: https://github.com/neovide/neovide/tree/fix-stuck-shift

It should fix this issue.

**Comment by songww** [comment]
@last-partizan  

> INFO [neovide::window::keyboard_manager] mods: CONTROL
> TRACE [neovide::redraw_scheduler] Next frame queued
> INFO [neovide::window::keyboard_manager] mods: (empty)
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::channel_utils] neovide::bridge::ui_commands::UiCommand Parallel(FocusLost)
> TRACE [neovide::channel_utils] neovide::bridge::ui_commands::UiCommand Parallel(FocusGained)
> TRACE [neovide::redraw_scheduler] Next frame queued
> INFO [neovide::window::keyboard_manager] mods: CONTROL
> TRACE [neovide::redraw_scheduler] Next frame queued
> TRACE [neovide::redraw_scheduler] Next frame queued

This is a log of once keystroke, and it looks like there is still a problem with the capture of this key.

**Comment by last-partizan** [comment]
Yeah, i see and i can reproduce this. I'll look into it again.

Btw, this is only on x11 backend, with wayland it works fine.

**Comment by last-partizan** [comment]
Oh, wait. Are you sure you have built `fix-stuck-shift` branch?

I just checked it, and it works just fine.

```
 nv --nofork 2>&1 | egrep '(mods|UiCommand)'
TRACE [neovide::channel_utils] neovide::bridge::ui_commands::UiCommand Parallel(FocusGained)
INFO [neovide::window::keyboard_manager] mods: (empty)
INFO [neovide::window::keyboard_manager] mods: ALT
INFO [neovide::window::keyboard_manager] mods: (empty)
INFO [neovide::window::keyboard_manager] mods: CONTROL
INFO [neovide::window::keyboard_manager] mods: (empty)
INFO [neovide::window::keyboard_manager] mods: CONTROL
INFO [neovide::window::keyboard_manager] mods: (empty)
INFO [neovide::window::keyboard_manager] mods: CONTROL
INFO [neovide::window::keyboard_manager] mods: (empty)
INFO [neovide::window::keyboard_manager] mods: CONTROL
INFO [neovide::window::keyboard_manager] mods: (empty)
INFO [neovide::window::keyboard_manager] mods: CONTROL
TRACE [neovide::channel_utils] neovide::bridge::ui_commands::UiCommand Serial(Keyboard("<C-a>"))
TRACE [neovide::channel_utils] neovide::bridge::ui_commands::UiCommand Serial(Keyboard("<C-a>"))
TRACE [neovide::channel_utils] neovide::bridge::ui_commands::UiCommand Serial(Keyboard("<C-a>"))
INFO [neovide::window::keyboard_manager] mods: (empty)
INFO [neovide::window::keyboard_manager] mods: CONTROL
INFO [neovide::window::keyboard_manager] mods: (empty)
INFO [neovide::window::keyboard_manager] mods: CONTROL
INFO [neovide::window::keyboard_manager] mods: (empty)
INFO [neovide::window::keyboard_manager] mods: CONTROL
INFO [neovide::window::keyboard_manager] mods: (empty)
TRACE [neovide::channel_utils] neovide::bridge::ui_commands::UiCommand Parallel(Quit)
```

What's strange - is the difference in FocusLost, for some reson in my log i don't see it.

**Comment by fredizzimo** [comment]
This should be fixed in Neovide 0.11
